[package]
name = "resonance-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
resonance-runtime = { path = "../../../crates/runtime" }
tauri = { version = "2.6.0", features = [] }

[lints]
workspace = true
