[package]
name = "resonance-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
debug-local-profiles = ["resonance-runtime/debug-local-profiles"]

[build-dependencies]
tauri-build = { version = "2.3.0", features = [] }

[dependencies]
fs2 = "0.4.3"
resonance-runtime = { path = "../../../crates/runtime" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tauri = { version = "2.6.0", features = [] }
tauri-plugin-dialog = "=2.2.2"
tauri-plugin-updater = "2.9.0"
tokio = { workspace = true, features = ["sync", "time"] }

[dev-dependencies]
tempfile = "3.14.0"

[lints]
workspace = true
